[WIP]Save my changes
Chiichen/GameVibes pull request #10
Opened 2024-06-22 13:36 UTC by H0924cc

2024-06-22 15:22 UTC, Chiichen requested changes

2024-06-22 15:22 UTC, Chiichen commented on app/src/main/java/cn/chiichen/gamevibes/ui/navigation/NavigationHost.kt
> +        composable("article") { ArticleDetailScreen(navController) }
要跳转到某个文章的页面怎么做，这个应该带一个路由参数吧

2024-06-22 15:22 UTC, Chiichen commented on app/src/main/java/cn/chiichen/gamevibes/ui/navigation/NavigationHost.kt
> +        composable("splash"){ SplashScreen(navController = navController, context = context)}
可以不用传context吧，在compose里用LocalContext

2024-06-22 15:25 UTC, H0924cc commented on app/src/main/java/cn/chiichen/gamevibes/ui/navigation/NavigationHost.kt
> +        composable("article") { ArticleDetailScreen(navController) }
晚点再写 还没想好怎么实现好一点

2024-06-22 15:25 UTC, H0924cc commented on app/src/main/java/cn/chiichen/gamevibes/ui/navigation/NavigationHost.kt
> +        composable("splash"){ SplashScreen(navController = navController, context = context)}
received

2024-06-26 14:58 UTC, Chiichen commented
@H0924cc Check Failed

2024-06-26 15:08 UTC, merged